In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
data_dir = Path("./scripts_survey_wifi/data")
csv_dir = data_dir / "archive/csv"

active = lambda author: csv_dir / f"active/active_L3_{author}.csv"
calibration = lambda author: csv_dir / f"calibration/kalibrasi_L3_{author}.csv"
passive = lambda author: csv_dir / f"passive/passive_L3_{author}.csv"

deva_active_path = active("Deva")
dinda_active_path = active("Dinda")
merged_active_path = data_dir / "active_L3.csv"

maul_cal_path = calibration("Maulana")
taqi_cal_path = calibration("Taqiya")
merged_cal_path = data_dir / "calibration_L3.csv"

maul_pass_path = passive("Maulana")
taqi_pass_path = passive("Taqiya")
merged_pass_path = data_dir / "passive_L3.csv"

# Active

In [11]:
deva_active = pd.read_csv(deva_active_path, sep=",", skip_blank_lines=True)
dinda_active = pd.read_csv(dinda_active_path, sep=",", skip_blank_lines=True)
merged_active = pd.concat([dinda_active, deva_active], ignore_index=True)
merged_active.head()

,timestamp,titik_id,bssid_assoc,freq_mhz,rssi_dbm,tx_rate_mbps,rtt_avg_ms,rtt_max_ms,jitter_ms,loss_pct,down_mbps,up_mbps,metode_rtt,device,scan_ke,lantai,catatan
0,2026-10-09T11:18:48,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.85,34.0,0.89,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
1,2026-10-09T11:19:13,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.50,33.0,1.37,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
2,2026-10-09T11:19:37,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,34.80,62.0,8.68,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
3,2026-10-09T11:20:06,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,31.30,40.0,2.11,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
4,2026-10-09T11:20:30,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,34.10,52.0,5.84,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN

In [12]:
merged_active.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     77 non-null     str
 1   titik_id      77 non-null     str
 2   bssid_assoc   76 non-null     str
 3   freq_mhz      73 non-null     float64
 4   rssi_dbm      73 non-null     float64
 5   tx_rate_mbps  76 non-null     float64
 6   rtt_avg_ms    60 non-null     float64
 7   rtt_max_ms    60 non-null     float64
 8   jitter_ms     60 non-null     float64
 9   loss_pct      77 non-null     float64
 10  down_mbps     0 non-null      float64
 11  up_mbps       0 non-null      float64
 12  metode_rtt    77 non-null     str
 13  device        77 non-null     str
 14  scan_ke       77 non-null     int64
 15  lantai        0 non-null      float64
 16  catatan       0 non-null      float64
dtypes: float64(11), int64(1), str(5)
memory usage: 10.4 KB

In [13]:
merged_active["timestamp"] = pd.to_datetime(merged_active["timestamp"])
merged_active.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     77 non-null     datetime64[us]
 1   titik_id      77 non-null     str
 2   bssid_assoc   76 non-null     str
 3   freq_mhz      73 non-null     float64
 4   rssi_dbm      73 non-null     float64
 5   tx_rate_mbps  76 non-null     float64
 6   rtt_avg_ms    60 non-null     float64
 7   rtt_max_ms    60 non-null     float64
 8   jitter_ms     60 non-null     float64
 9   loss_pct      77 non-null     float64
 10  down_mbps     0 non-null      float64
 11  up_mbps       0 non-null      float64
 12  metode_rtt    77 non-null     str
 13  device        77 non-null     str
 14  scan_ke       77 non-null     int64
 15  lantai        0 non-null      float64
 16  catatan       0 non-null      float64
dtypes: datetime64[us](1), float64(11), int64(1), str(4)
memory usage: 10.4 KB

In [14]:
# sort merged berdasarkan timestamp
tmp = merged_active.sort_values(by="timestamp", ascending=True).reset_index().drop(columns="index")
tmp.head(20)

,timestamp,titik_id,bssid_assoc,freq_mhz,rssi_dbm,tx_rate_mbps,rtt_avg_ms,rtt_max_ms,jitter_ms,loss_pct,down_mbps,up_mbps,metode_rtt,device,scan_ke,lantai,catatan
0,2026-10-09 11:17:04,L3-004,54:d7:e3:41:42:d0,5745.0,-56.0,117.0,33.36,63.9,5.01,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
1,2026-10-09 11:17:17,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,117.0,33.86,50.8,5.05,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
2,2026-10-09 11:17:30,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,32.66,62.6,3.54,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
3,2026-10-09 11:17:43,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,33.51,66.8,5.08,0.0,NaN,NaN,icmp,devCore,4,NaN,NaN
4,2026-10-09 11:17:56,L3-004,54:d7:e3:41:42:d0,5745.0,-52.0,573.5,33.36,54.8,4.59,0.0,NaN,NaN,icmp,devCore,5,NaN,NaN
5,2026-10-09 11:18:42,L3-002,54:d7:e3:41:42:d0,5745.0,-63.0,29.2,33.16,49.0,2.98,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
6,2026-10-09 11:18:48,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.85,34.0,0.89,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
7,2026-10-09 11:18:56,L3-002,54:d7:e3:41:42:d0,5745.0,-57.0,29.2,32.30,49.5,3.49,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
8,2026-10-09 11:19:09,L3-002,54:d7:e3:41:42:d0,5745.0,-62.0,29.2,31.40,37.1,1.19,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
9,2026-10-09 11:19:13,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.50,33.0,1.37,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
10,2026-10-09 11:19:22,L3-002,54:d7:e3:41:42:d0,5745.0,-59.0,29.2,30.71,41.7,2.66,0.0,NaN,NaN,icmp,devCore,4,NaN,NaN
11,2026-10-09 11:19:35,L3-002,54:d7:e3:41:42:d0,5745.0,-56.0,487.5,32.25,48.4,2.70,0.0,NaN,NaN,icmp,devCore,5,NaN,NaN
12,2026-10-09 11:19:37,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,34.80,62.0,8.68,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
13,2026-10-09 11:20:06,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,31.30,40.0,2.11,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
14,2026-10-09 11:20:30,L3-029,fc:7f:f1:dd:53:30,5320.0,-55.0,573.5,34.10,52.0,5.84,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
15,2026-10-09 11:20:47,L3-006,54:d7:e3:41:42:d0,5745.0,-66.0,29.2,79.31,632.0,43.84,30.0,NaN,NaN,icmp,devCore,1,NaN,NaN
16,2026-10-09 11:21:00,L3-006,54:d7:e3:42:97:90,5180.0,-57.0,117.0,32.47,61.2,4.65,34.0,NaN,NaN,icmp,devCore,2,NaN,NaN
17,2026-10-09 11:21:24,L3-006,54:d7:e3:42:97:90,5180.0,-56.0,117.0,31.22,43.0,1.74,22.0,NaN,NaN,icmp,devCore,3,NaN,NaN
18,2026-10-09 11:21:37,L3-006,54:d7:e3:42:97:90,5180.0,-61.0,541.6,30.79,49.2,2.70,38.0,NaN,NaN,icmp,devCore,4,NaN,NaN
19,2026-10-09 11:21:46,L3-006,54:d7:e3:42:97:90,5180.0,-62.0,541.6,NaN,NaN,NaN,100.0,NaN,NaN,tcp443,devCore,5,NaN,NaN

In [15]:
merged_active = tmp.copy()
merged_active.head(10)

,timestamp,titik_id,bssid_assoc,freq_mhz,rssi_dbm,tx_rate_mbps,rtt_avg_ms,rtt_max_ms,jitter_ms,loss_pct,down_mbps,up_mbps,metode_rtt,device,scan_ke,lantai,catatan
0,2026-10-09 11:17:04,L3-004,54:d7:e3:41:42:d0,5745.0,-56.0,117.0,33.36,63.9,5.01,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
1,2026-10-09 11:17:17,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,117.0,33.86,50.8,5.05,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
2,2026-10-09 11:17:30,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,32.66,62.6,3.54,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
3,2026-10-09 11:17:43,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,33.51,66.8,5.08,0.0,NaN,NaN,icmp,devCore,4,NaN,NaN
4,2026-10-09 11:17:56,L3-004,54:d7:e3:41:42:d0,5745.0,-52.0,573.5,33.36,54.8,4.59,0.0,NaN,NaN,icmp,devCore,5,NaN,NaN
5,2026-10-09 11:18:42,L3-002,54:d7:e3:41:42:d0,5745.0,-63.0,29.2,33.16,49.0,2.98,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
6,2026-10-09 11:18:48,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.85,34.0,0.89,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
7,2026-10-09 11:18:56,L3-002,54:d7:e3:41:42:d0,5745.0,-57.0,29.2,32.30,49.5,3.49,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
8,2026-10-09 11:19:09,L3-002,54:d7:e3:41:42:d0,5745.0,-62.0,29.2,31.40,37.1,1.19,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
9,2026-10-09 11:19:13,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.50,33.0,1.37,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN

In [17]:
merged_active.to_csv(merged_active_path, sep=",", index=False)
pd.read_csv(merged_active_path).head(10)

,timestamp,titik_id,bssid_assoc,freq_mhz,rssi_dbm,tx_rate_mbps,rtt_avg_ms,rtt_max_ms,jitter_ms,loss_pct,down_mbps,up_mbps,metode_rtt,device,scan_ke,lantai,catatan
0,2026-10-09 11:17:04,L3-004,54:d7:e3:41:42:d0,5745.0,-56.0,117.0,33.36,63.9,5.01,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
1,2026-10-09 11:17:17,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,117.0,33.86,50.8,5.05,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
2,2026-10-09 11:17:30,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,32.66,62.6,3.54,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
3,2026-10-09 11:17:43,L3-004,54:d7:e3:41:42:d0,5745.0,-53.0,573.5,33.51,66.8,5.08,0.0,NaN,NaN,icmp,devCore,4,NaN,NaN
4,2026-10-09 11:17:56,L3-004,54:d7:e3:41:42:d0,5745.0,-52.0,573.5,33.36,54.8,4.59,0.0,NaN,NaN,icmp,devCore,5,NaN,NaN
5,2026-10-09 11:18:42,L3-002,54:d7:e3:41:42:d0,5745.0,-63.0,29.2,33.16,49.0,2.98,0.0,NaN,NaN,icmp,devCore,1,NaN,NaN
6,2026-10-09 11:18:48,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.85,34.0,0.89,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN
7,2026-10-09 11:18:56,L3-002,54:d7:e3:41:42:d0,5745.0,-57.0,29.2,32.30,49.5,3.49,0.0,NaN,NaN,icmp,devCore,2,NaN,NaN
8,2026-10-09 11:19:09,L3-002,54:d7:e3:41:42:d0,5745.0,-62.0,29.2,31.40,37.1,1.19,0.0,NaN,NaN,icmp,devCore,3,NaN,NaN
9,2026-10-09 11:19:13,L3-029,fc:7f:f1:dd:53:30,NaN,NaN,573.5,30.50,33.0,1.37,0.0,NaN,NaN,icmp,LAPTOP-GC8OEJA7,1,NaN,NaN

# Passive

In [23]:
taqi_pass = pd.read_csv(taqi_pass_path, sep=",")
maul_pass = pd.read_csv(maul_pass_path, sep=",")

merged_pass = pd.concat([taqi_pass, maul_pass], ignore_index=True)
merged_pass.head()

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09T07:51:24,NaN,L3-027,NaN,NaN,T1,laptop-taqiya,1,WiFi-UB.x,54:d7:e3:45:51:20,...,1,2.4,20,-47.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09T07:51:24,NaN,L3-027,NaN,NaN,T1,laptop-taqiya,1,ㅤ,d6:7a:83:ec:10:18,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2/WPA3-Personal,capable,NaN
2,2026-10-09T07:51:24,NaN,L3-027,NaN,NaN,T1,laptop-taqiya,1,iPhone (2),ba:52:1a:fe:b4:8c,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
3,2026-10-09T07:51:24,NaN,L3-027,NaN,NaN,T1,laptop-taqiya,1,Kfkfkfm,46:d9:d2:ca:4f:5a,...,6,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09T07:51:24,NaN,L3-027,NaN,NaN,T1,laptop-taqiya,1,Xiaomi 12T,aa:e0:aa:9c:66:21,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN

In [24]:
merged_pass.info()

<class 'pandas.DataFrame'>
RangeIndex: 3157 entries, 0 to 3156
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    3157 non-null   str
 1   lantai       0 non-null      float64
 2   titik_id     3157 non-null   str
 3   x_px         0 non-null      float64
 4   y_px         0 non-null      float64
 5   slot_waktu   3157 non-null   str
 6   device       3157 non-null   str
 7   scan_ke      3157 non-null   int64
 8   ssid         3128 non-null   str
 9   bssid        3157 non-null   str
 10  freq_mhz     3157 non-null   int64
 11  channel      3157 non-null   int64
 12  band         3157 non-null   float64
 13  width_mhz    3157 non-null   int64
 14  rssi_dbm     3157 non-null   float64
 15  noise_dbm    721 non-null    float64
 16  sta_count    519 non-null    float64
 17  ch_util_pct  519 non-null    float64
 18  security     3157 non-null   str
 19  pmf          3157 non-null   str
 20  catatan      0 non-null      float64
dtypes: float64(9), int64(4), str(8)
memory usage: 518.1 KB

In [25]:
merged_pass["timestamp"] = pd.to_datetime(merged_pass["timestamp"])

merged_pass.info()

<class 'pandas.DataFrame'>
RangeIndex: 3157 entries, 0 to 3156
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    3157 non-null   datetime64[us]
 1   lantai       0 non-null      float64
 2   titik_id     3157 non-null   str
 3   x_px         0 non-null      float64
 4   y_px         0 non-null      float64
 5   slot_waktu   3157 non-null   str
 6   device       3157 non-null   str
 7   scan_ke      3157 non-null   int64
 8   ssid         3128 non-null   str
 9   bssid        3157 non-null   str
 10  freq_mhz     3157 non-null   int64
 11  channel      3157 non-null   int64
 12  band         3157 non-null   float64
 13  width_mhz    3157 non-null   int64
 14  rssi_dbm     3157 non-null   float64
 15  noise_dbm    721 non-null    float64
 16  sta_count    519 non-null    float64
 17  ch_util_pct  519 non-null    float64
 18  security     3157 non-null   str
 19  pmf          3157 non-null   str
 20  catatan      0 non-null      float64
dtypes: datetime64[us](1), float64(9), int64(4), str(7)
memory usage: 518.1 KB

In [26]:
merged_pass["lantai"] = 3
merged_pass.head()

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,WiFi-UB.x,54:d7:e3:45:51:20,...,1,2.4,20,-47.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,ㅤ,d6:7a:83:ec:10:18,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2/WPA3-Personal,capable,NaN
2,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,iPhone (2),ba:52:1a:fe:b4:8c,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
3,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,Kfkfkfm,46:d9:d2:ca:4f:5a,...,6,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,Xiaomi 12T,aa:e0:aa:9c:66:21,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN

In [27]:
merged_pass.to_csv(merged_pass_path, sep=",", index=False)

pd.read_csv(merged_pass_path).head(10)

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,WiFi-UB.x,54:d7:e3:45:51:20,...,1,2.4,20,-47.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,ㅤ,d6:7a:83:ec:10:18,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2/WPA3-Personal,capable,NaN
2,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,iPhone (2),ba:52:1a:fe:b4:8c,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
3,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,Kfkfkfm,46:d9:d2:ca:4f:5a,...,6,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,Xiaomi 12T,aa:e0:aa:9c:66:21,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
5,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,echa,5a:0a:10:1a:1c:cc,...,6,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
6,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,nanadd,4e:f9:04:44:27:54,...,1,2.4,20,-80.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
7,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,©®⅞,e6:ce:60:56:6a:41,...,1,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
8,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,WiFi-FILKOM,54:d7:e3:45:51:31,...,52,5.0,40,-84.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
9,2026-10-09 07:51:24,3,L3-027,NaN,NaN,T1,laptop-taqiya,1,WiFi-FILKOM,e8:10:98:82:05:a1,...,157,5.0,40,-87.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN

# Calibration

In [28]:
maul_cal = pd.read_csv(maul_cal_path, sep=",")
taqi_cal = pd.read_csv(taqi_cal_path, sep=",")

merged_cal = pd.concat([taqi_cal, maul_cal], ignore_index=True)
merged_cal.head()

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09T07:43:08,NaN,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:30,...,64,5.0,40,-60.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09T07:43:08,NaN,L3-001,NaN,NaN,T0,laptop-taqiya,1,Lia's Galaxy A33 5G,52:ae:52:22:ad:64,...,11,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
2,2026-10-09T07:43:08,NaN,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:20,...,11,2.4,20,-71.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
3,2026-10-09T07:43:08,NaN,L3-001,NaN,NaN,T0,laptop-taqiya,1,Unite Plaechere,42:3d:77:b0:7e:9e,...,11,2.4,20,-70.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09T07:43:08,NaN,L3-001,NaN,NaN,T0,laptop-taqiya,1,NaN,c2:99:ab:bd:f4:e6,...,6,2.4,20,-49.0,NaN,NaN,NaN,WPA2-Personal,no,NaN

In [29]:
merged_cal.info()

<class 'pandas.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    237 non-null    str
 1   lantai       0 non-null      float64
 2   titik_id     237 non-null    str
 3   x_px         0 non-null      float64
 4   y_px         0 non-null      float64
 5   slot_waktu   237 non-null    str
 6   device       237 non-null    str
 7   scan_ke      237 non-null    int64
 8   ssid         231 non-null    str
 9   bssid        237 non-null    str
 10  freq_mhz     237 non-null    int64
 11  channel      237 non-null    int64
 12  band         237 non-null    float64
 13  width_mhz    237 non-null    int64
 14  rssi_dbm     237 non-null    float64
 15  noise_dbm    93 non-null     float64
 16  sta_count    19 non-null     float64
 17  ch_util_pct  19 non-null     float64
 18  security     237 non-null    str
 19  pmf          237 non-null    str
 20  catatan      0 non-null      float64
dtypes: float64(9), int64(4), str(8)
memory usage: 39.0 KB

In [30]:
merged_cal["lantai"] = 3
merged_cal.head(10)

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:30,...,64,5.0,40,-60.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Lia's Galaxy A33 5G,52:ae:52:22:ad:64,...,11,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
2,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:20,...,11,2.4,20,-71.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
3,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Unite Plaechere,42:3d:77:b0:7e:9e,...,11,2.4,20,-70.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,NaN,c2:99:ab:bd:f4:e6,...,6,2.4,20,-49.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
5,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Redmi 10C,4e:78:64:e6:2c:5c,...,5,2.4,20,-78.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
6,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,kuonzx,96:27:be:d6:7a:73,...,6,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
7,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Kfkfkfm,46:d9:d2:ca:4f:5a,...,6,2.4,20,-62.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
8,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,FILKOM EVENT,54:d7:e3:45:51:23,...,1,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
9,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,eduroam,54:d7:e3:45:51:22,...,1,2.4,20,-73.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN

In [31]:
merged_cal.to_csv(merged_cal_path, sep=",", index=False)
pd.read_csv(merged_cal_path, sep=",").head(10)

,timestamp,lantai,titik_id,x_px,y_px,slot_waktu,device,scan_ke,ssid,bssid,...,channel,band,width_mhz,rssi_dbm,noise_dbm,sta_count,ch_util_pct,security,pmf,catatan
0,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:30,...,64,5.0,40,-60.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
1,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Lia's Galaxy A33 5G,52:ae:52:22:ad:64,...,11,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
2,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,WiFi-UB.x,fc:7f:f1:dd:53:20,...,11,2.4,20,-71.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN
3,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Unite Plaechere,42:3d:77:b0:7e:9e,...,11,2.4,20,-70.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
4,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,NaN,c2:99:ab:bd:f4:e6,...,6,2.4,20,-49.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
5,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Redmi 10C,4e:78:64:e6:2c:5c,...,5,2.4,20,-78.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
6,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,kuonzx,96:27:be:d6:7a:73,...,6,2.4,20,-68.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
7,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,Kfkfkfm,46:d9:d2:ca:4f:5a,...,6,2.4,20,-62.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
8,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,FILKOM EVENT,54:d7:e3:45:51:23,...,1,2.4,20,-75.0,NaN,NaN,NaN,WPA2-Personal,no,NaN
9,2026-10-09T07:43:08,3,L3-001,NaN,NaN,T0,laptop-taqiya,1,eduroam,54:d7:e3:45:51:22,...,1,2.4,20,-73.0,NaN,NaN,NaN,WPA2/3-Enterprise,no,NaN